### ISSUE TITLE
parse failed undefined method `emit' for #<Fluent::Plugin::MemoryBuffer:0055af2e94ab28>

### ISSUE THREAD

**Issue by funwun** [fluent/fluentd#1099]
Check [CONTRIBUTING guideline](https://github.com/fluent/fluentd/blob/master/CONTRIBUTING.md) first and here is the list to help us investigate the problem.

- fluentd or td-agent version.

fluentd: 0.14.1
fluent-plugin-parser: v0.6.1
- Environment information, e.g. OS.

alpine linux
- Your configuration
```
<match docker.nginx-**.error>
    @type parser
    key_name log
    format /^(?<time>[^ ]+ [^ ]+) \[(?<level>.*)\] (?<pid>\d*).(?<tid>[^:]*): (?<message>.*)$/
    remove_prefix docker
    reserve_data yes
</match>
```

- Your problem explanation. If you have an error logs, write it together.

[warn]: parse failed undefined method `emit' for #<Fluent::Plugin::MemoryBuffer:0055af2e94ab28>
[warn]: suppressed same stacktrace

fluentd 0.12.26 is ok.

**Comment by repeatedly** [comment]
It seems parser plugin doesn't have a problem because parser plugin doesn't use buffer plugin.
Could you paste your entire logs?

I tested it parser plugin and it worked on v0.14.1.

```
% fluentd -c v014-parser.conf
2016-07-13 16:07:17 +0900 [info]: reading config file path="v014-parser.conf"
2016-07-13 16:07:17 +0900 [info]: starting fluentd-0.14.1
2016-07-13 16:07:17 +0900 [info]: spawn command to main: /Users/repeatedly/.rbenv/versions/2.3.1/bin/ruby -Eascii-8bit:ascii-8bit /Users/repeatedly/.rbenv/versions/2.3.1/bin/fluentd -c v014-parser.conf --under-supervisor
2016-07-13 16:07:18 +0900 [info]: reading config file path="v014-parser.conf"
2016-07-13 16:07:18 +0900 [info]: starting fluentd-0.14.1 without supervision
[snip]
2016-07-13 16:07:18 +0900 [info]: gem 'fluent-plugin-parser' version '0.6.1'
[snip]
2016-07-13 16:07:18 +0900 [info]: gem 'fluentd' version '0.14.1'
2016-07-13 16:07:18 +0900 [info]: gem 'fluentd' version '0.12.26'
2016-07-13 16:07:18 +0900 [info]: adding match pattern="docker.error" type="parser"
2016-07-13 16:07:18 +0900 [info]: adding match pattern="**" type="stdout"
2016-07-13 16:07:18 +0900 [info]: adding source type="forward"
2016-07-13 16:07:18 +0900 [info]: using configuration file: <ROOT>
  <source>
    @type forward
  </source>
  <match docker.error>
    @type parser
    key_name "log"
    format none
    remove_prefix "docker"
    reserve_data yes
  </match>
  <match **>
    @type stdout
  </match>
</ROOT>
2016-07-13 16:07:18 +0900 [info]: listening fluent socket on 0.0.0.0:24224
2016-07-13 16:07:40 +0900 error: {"log":"test","message":"test"}
```

**Comment by funwun** [comment]
this plugins I used.

fluent-mixin-config-placeholders (0.4.0)
fluent-plugin-elasticsearch (1.5.0)
fluent-plugin-filter_typecast (0.0.2)
fluent-plugin-forest (0.3.0)
fluent-plugin-parser (0.6.1)
fluent-plugin-record-modifier (0.4.1)
fluent-plugin-rewrite-tag-filter (1.5.5)
fluentd (0.12.26)

**Comment by repeatedly** [comment]
I mean fluentd/td-agent log, not plugin list.

**Comment by repeatedly** [comment]
ping?
